In [2]:
# from pathlib import Path, PureWindowsPath # For windows only 
import os 
import pandas as pd
import time
from time import sleep
import selenium #Need this step 
from selenium import webdriver #Need this step 

from selenium.webdriver.common.by import By #Allows for selenium to click things 
from selenium.webdriver.chrome.service import Service #https://stackoverflow.com/questions/64717302/deprecationwarning-executable-path-has-been-deprecated-selenium-python
from selenium.webdriver.support import expected_conditions as EC #Allows for more complex code 
from selenium.webdriver.chrome.options import Options #Allows you to change aspects of the browser

# Establish options we can change
chrome_options = Options()

In [3]:
chrome_options.add_argument("--window-size=1900,1000") #pick a size and stick with it, it can change how code intreacts with the website.
driver = webdriver.Chrome(options = chrome_options) #establish driver

In [4]:
url = 'https://lolalytics.com/lol/tierlist/'
driver.get(url) # Get the url
# Source - https://stackoverflow.com/a/27760083
# Posted by OWADVL, modified by community. See post 'Timeline' for change history
# Retrieved 2026-04-15, License - CC BY-SA 4.0

driver.execute_script("window.scrollTo(0, document.body.scrollHeight);") # scrolls to the very bottom of the page to load everything (takes ~20 seconds)
time.sleep(5) # want to wait 10 seconds to let things load
driver.execute_script("window.scrollBy(0, -6000);") # scrolls back up to load everything
for i in range(0,20): # scrolls downs for the next twenty seconds to make sure everything loads
    driver.execute_script("window.scrollBy(0, 300);")
    time.sleep(1)

In [5]:
buckets = driver.find_elements(By.XPATH, '/html/body/main/div[6]/div') # creating bucket of each thing
del buckets[:2]
buckets[160].text

'68\nZaahen\nC+\n63.13\n50.09\n+1.41\n3.04\n5.38\n-3\n7,630\n101\n54.79\n2,024\n4.70\nGM'

In [6]:
buckets[171].text # testing

'94\nTrundle\nD+\n64.97\n50.02\n+1.49\n1.14\n0.31\n-1\n2,871\n170\n54.82\n1,503\n4.80\nD I'

In [23]:
driver.find_elements(By.XPATH, '/html/body/main/div[6]/div[3]/div[5]/div/img')[0].get_attribute('alt')

'top lane'

In [24]:
import time            # importing time package
start=time.time()      # start time

out = []
count = 3

for bucket in buckets:
    champion = driver.find_elements(By.XPATH, f'/html/body/main/div[6]/div[{count}]/div[3]/a')[0].text
    wr = driver.find_elements(By.XPATH, f'/html/body/main/div[6]/div[{count}]/div[6]/div/span')[0].text
    
    temp= driver.find_elements(By.XPATH, f'/html/body/main/div[6]/div[{count}]/div[6]/div/span')
    wrdelta= temp[1].text if len(temp) > 1 else 0 # checks to see if there is an entry for wrdelta (some are missing on the website)

    pick = driver.find_elements(By.XPATH, f'/html/body/main/div[6]/div[{count}]/div[7]')[0].text
    ban = driver.find_elements(By.XPATH, f'/html/body/main/div[6]/div[{count}]/div[8]')[0].text
    PBI = driver.find_elements(By.XPATH, f'/html/body/main/div[6]/div[{count}]/div[9]')[0].text
    lane = driver.find_elements(By.XPATH, f'/html/body/main/div[6]/div[{count}]/div[5]/div/img')[0].get_attribute('alt')
    
    data = {
        'Champion':champion,
        'wr':wr,
        'wrdelta':wrdelta,
        'Pick Rate':pick,
        'Ban Rate':ban,
        'PBI Index':PBI,
        'lane':lane
    }
    out.append(data)
    count = count+1

end=time.time()        # end time

total_time=end-start   # measures total time by subtracting start by end
print(f' The code takes {round(total_time,5)} seconds to run.')

 The code takes 34.71519 seconds to run.

In [25]:
outdf=pd.DataFrame(out)
outdf

         Champion     wr wrdelta Pick Rate Ban Rate PBI Index          lane
0            Olaf  53.48   +1.66      2.35     2.24         6      top lane
1            Jinx  53.37   +1.11     14.38     4.57        34   bottom lane
2            Bard  51.64   +0.79      6.68     3.10         4  support lane
3         Naafiri  52.07   +1.40      7.12    22.15         9   jungle lane
4            Shen  52.81   +1.35      4.38     2.69         8      top lane
..            ...    ...     ...       ...      ...       ...           ...
167       K'Sante  48.60   +1.02      3.88     2.32       -10      top lane
168         Jayce  49.37   +0.81      5.26     5.96       -10      top lane
169  Heimerdinger  50.54   +1.06      1.13     1.62        -1      top lane
170           Mel  45.43   +1.33      4.60    36.71       -41   middle lane
171       Trundle  50.02   +1.49      1.14     0.31        -1      top lane

[172 rows x 7 columns]

In [26]:
outdf['wrdelta']=pd.to_numeric(outdf['wrdelta'])
outdf['wr']=pd.to_numeric(outdf['wr'])

In [27]:
outdf['avgwr']=outdf['wr']-outdf['wrdelta']
outdf

,Champion,wr,wrdelta,Pick Rate,Ban Rate,PBI Index,lane,avgwr
0,Olaf,53.48,1.66,2.35,2.24,6,top lane,51.82
1,Jinx,53.37,1.11,14.38,4.57,34,bottom lane,52.26
2,Bard,51.64,0.79,6.68,3.10,4,support lane,50.85
3,Naafiri,52.07,1.40,7.12,22.15,9,jungle lane,50.67
4,Shen,52.81,1.35,4.38,2.69,8,top lane,51.46
...,...,...,...,...,...,...,...,...
167,K'Sante,48.60,1.02,3.88,2.32,-10,top lane,47.58
168,Jayce,49.37,0.81,5.26,5.96,-10,top lane,48.56
169,Heimerdinger,50.54,1.06,1.13,1.62,-1,top lane,49.48
170,Mel,45.43,1.33,4.60,36.71,-41,middle lane,44.10
171,Trundle,50.02,1.49,1.14,0.31,-1,top lane,48.53

In [28]:
outdf.to_csv('league.csv', index=False)